#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwkApi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dwk-multiple-projects")]
	public partial class TT2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TT2DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dwk_multiple_projectsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TT2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TT2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TT2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TT2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TimerModel> TimerModels
		{
			get
			{
				return this.GetTable<TimerModel>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt2.AddRootTimer")]
		public ISingleResult<TimerModel> AddRootTimer()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TimerModel>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt2.AddTimer")]
		public ISingleResult<TimerModel> AddTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentKey", DbType="Char(36)")] string parentKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parentKey);
			return ((ISingleResult<TimerModel>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt2.AdjustTimer")]
		public ISingleResult<TimerModel> AdjustTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Key", DbType="Char(36)")] string key, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Seconds", DbType="Int")] System.Nullable<int> seconds)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key, seconds);
			return ((ISingleResult<TimerModel>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt2.DeleteTimer")]
		public ISingleResult<TimerModel> DeleteTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Key", DbType="Char(36)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<TimerModel>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt2.GetChildren")]
		public ISingleResult<TimerModel> GetChildren([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentKey", DbType="Char(36)")] string parentKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parentKey);
			return ((ISingleResult<TimerModel>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt2.GetTimer")]
		public ISingleResult<TimerModel> GetTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerKey", DbType="Char(36)")] string timerKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), timerKey);
			return ((ISingleResult<TimerModel>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt2.RenameTimer")]
		public ISingleResult<TimerModel> RenameTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Key", DbType="Char(36)")] string key, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewName", DbType="NVarChar(150)")] string newName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key, newName);
			return ((ISingleResult<TimerModel>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt2.ResetTimer")]
		public ISingleResult<TimerModel> ResetTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Key", DbType="Char(36)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<TimerModel>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt2.ToggleTimer")]
		public ISingleResult<TimerModel> ToggleTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerKey", DbType="Char(36)")] string timerKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), timerKey);
			return ((ISingleResult<TimerModel>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tt2.TimerModel")]
	public partial class TimerModel
	{
		
		private string _TimerKey;
		
		private string _ReadOnlyKey;
		
		private string _TimerName;
		
		private System.Nullable<bool> _IsRunning;
		
		private System.Nullable<int> _ChildCount;
		
		private System.Nullable<System.DateTime> _CreationTime;
		
		private System.Nullable<int> _ElapsedTime;
		
		private System.Nullable<bool> _IsReadOnly;
		
		public TimerModel()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimerKey", DbType="Char(36)")]
		public string TimerKey
		{
			get
			{
				return this._TimerKey;
			}
			set
			{
				if ((this._TimerKey != value))
				{
					this._TimerKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadOnlyKey", DbType="Char(36)")]
		public string ReadOnlyKey
		{
			get
			{
				return this._ReadOnlyKey;
			}
			set
			{
				if ((this._ReadOnlyKey != value))
				{
					this._ReadOnlyKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimerName", DbType="NVarChar(150)")]
		public string TimerName
		{
			get
			{
				return this._TimerName;
			}
			set
			{
				if ((this._TimerName != value))
				{
					this._TimerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRunning", DbType="Bit")]
		public System.Nullable<bool> IsRunning
		{
			get
			{
				return this._IsRunning;
			}
			set
			{
				if ((this._IsRunning != value))
				{
					this._IsRunning = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChildCount", DbType="Int")]
		public System.Nullable<int> ChildCount
		{
			get
			{
				return this._ChildCount;
			}
			set
			{
				if ((this._ChildCount != value))
				{
					this._ChildCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTime
		{
			get
			{
				return this._CreationTime;
			}
			set
			{
				if ((this._CreationTime != value))
				{
					this._CreationTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElapsedTime", DbType="Int")]
		public System.Nullable<int> ElapsedTime
		{
			get
			{
				return this._ElapsedTime;
			}
			set
			{
				if ((this._ElapsedTime != value))
				{
					this._ElapsedTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReadOnly", DbType="Bit")]
		public System.Nullable<bool> IsReadOnly
		{
			get
			{
				return this._IsReadOnly;
			}
			set
			{
				if ((this._IsReadOnly != value))
				{
					this._IsReadOnly = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
